function Hd = lowpass
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 10-Feb-2021 00:57:07

Fpass = 1000;   % Passband Frequency
Fstop = 12000;  % Stopband Frequency
Apass = 1;      % Passband Ripple (dB)
Astop = 10;     % Stopband Attenuation (dB)
Fs    = 48000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);


