function y = lowpassbass(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 10-Feb-2021 15:34:00

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 800;    % Passband Frequency
    % Fstop = 1000;   % Stopband Frequency
    % Apass = 1;      % Passband Ripple (dB)
    % Astop = 30;     % Stopband Attenuation (dB)
    % Fs    = 44100;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.96663181911825 0.980605634829726; 1 2 1 1 ...
        -1.92971662697755 0.943428143418313; 1 2 1 1 -1.89559738503733 ...
        0.909066468708293; 1 2 1 1 -1.86493644081554 0.87818766449871; 1 2 1 1 ...
        -1.83825697665118 0.851318630577631; 1 2 1 1 -1.81596059400813 ...
        0.828863821970417; 1 2 1 1 -1.79834577077889 0.811123837391098; 1 2 1 1 ...
        -1.78562501684544 0.798312696701242; 1 2 1 1 -1.77793927990389 ...
        0.790572349094603; 1 1 0 1 -0.887684354967378 0], ...
        'ScaleValues', [0.00349345392786972; 0.00342787911018992; ...
        0.00336727091773962; 0.00331280592079279; 0.00326541348161207; ...
        0.00322580699057269; 0.00319451665305211; 0.00317191996395034; ...
        0.00315826729767798; 0.0561578225163112; 1]);
end

s = double(x);
y = step(Hd,s);

